name: clean_architecture
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  card_swiper: ^2.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.4.0+1
  flutter_slidable: ^1.2.0
  flutter_spinkit: ^5.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  timeago: ^3.2.2
  top_snackbar_flutter: ^1.0.2
  url_launcher: ^6.1.0
  webfeed: ^0.7.0
  webview_flutter: ^3.0.2

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.1
  mockito: ^5.1.0

flutter:
  uses-material-design: true
